apiVersion: batch/v1
kind: Job
metadata:
  name: performance-test-job
  namespace: poc
spec:
  template:
    spec:
      containers:
      - name: performance-test
        image: 314201/performance-test
        imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 4
