apiVersion: v1
kind: Service
metadata:
  name: echo-server-service
  namespace: poc
spec:
  selector:
    app: echo-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
